# Generated by Django 5.2 on 2025-05-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exercise_id_alter_food_entry_calories_and_more'),
        ('exlog_app', '0003_exercise_foreignkey_to_app_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercise', verbose_name='Упражнение'),
        ),
    ]
