services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: activitywatch
      POSTGRES_USER: activitywatch
      POSTGRES_PASSWORD: activitywatch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn ActivityWatch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/var/www/activitywatch/staticfiles:ro
      - ./media:/var/www/activitywatch/media:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  pgdata:
  static_volume:
  media_volume:
