[project]
name = "activitywatch-1-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "matplotlib>=3.10.1",
    "psycopg2-binary>=2.9.10",
    "python-decouple>=3.8",
]
