# Generated by Django 5.2 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exercise_id_alter_food_entry_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='group_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_link',
            field=models.TextField(blank=True, default='https://example.com/default-image.png', null=True),
        ),
    ]
