# Generated by Django 5.2 on 2025-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exercise_group_code_alter_exercise_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='exerciseImages/'),
        ),
    ]
